### ISSUE TITLE
升级到 2.0.0 会导致选项页异常而无法显示的问题

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#1014]
RT 应该是隐性 Bug 出错时控制台打印以下内容

```
Error handling response: TypeError: Cannot read property 'trigger' of undefined
    at n.value (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/options.js:11:20537)
    at c._renderValidatedComponentWithoutOwnerOrContext (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:15045)
    at c._renderValidatedComponent (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:15133)
    at c.mountComponent (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:11383)
    at Object.mountComponent (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:5:6619)
    at g.mountChildren (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:24:3444)
    at g._createContentMarkup (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:21489)
    at g.mountComponent (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:20446)
    at Object.mountComponent (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:5:6619)
    at g.mountChildren (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:24:3444)
    at g._createContentMarkup (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:21489)
    at g.mountComponent (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:20446)
    at Object.mountComponent (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:5:6619)
    at g.mountChildren (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:24:3444)
    at g._createContentMarkup (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:21489)
    at g.mountComponent (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:20446)
```
经查证，应该是 `labs.jsx` 出现错误

```
    componentDidMount() {
        this.exclusionState( this.props.read.auto );
        this.tocState( this.props.read.toc );
        this.cleanupState( this.props.read.cleanup == undefined ? true : this.props.read.cleanup );
        this.lazyloadState( this.props.option.preload );
        this.annoteState( this.props.option.annote.trigger );  <-------出错位置
    }
```

**Comment by QuentinHsu** [comment]
我也遇到该问题

**Comment by Kenshin** [comment]
@QuentinHsu 
可以解决的，请访问 https://github.com/Kenshin/simpread/issues/908

并留意 #6 的说明

***

这个 Issues 是我自己开的，用于追踪。 😀

**Comment by Kenshin** [comment]
简悦已升级到 [2.1.0](http://ksria.com/simpread/welcome/version_2.1.0.html) 版本

解决了此类问题，当出现未知错误导致选项页无法打开的话，会提示并可手动下载配置文件，以确保你的数据仍旧留存。

***

简悦 2.1 目前正在做最后一天的折扣 **10元**，有需要的话请前往购买 👉 https://simpread.pro/price.html

***

## 增加了一些新功能：

 - 简悦 · 同步助手
    是随着 简悦 2.1.0 发布的一个全新的【桌面应用】，用于对简悦已知功能的补充，以及会持续提供更多的可玩性，包括：
    - 自动同步
    - 导出到本地任意目录
    - 原生的 PDF · Epub 输出
    - 邮件服务
    - 直接发送到 Kindle
    - 小书签
    详见 👉 http://ksria.com/simpread/docs/#/Sync

 - 自动同步
    通过此功能，简悦可以将【配置文件保存到本地的任意位置】，同时辅以【网盘同步】功能，可以实现自动同步的功能，详见 👉 http://ksria.com/simpread/docs/#/自动同步

 - 授权登录
    简悦的【账户系统】来了，你可以使用【坚果云 或 Dropbox】登录你的【简悦 · 高级账户】了，如何配置，详见 👉 http://ksria.com/simpread/docs/#/授权登录

 - 每日回顾
    简悦会在【每天晚上 19点10分】给你的邮箱发送一封二十四小时以内添加的稍后读，用作当天的每日回顾，同时发送内容也适配了手机端，借此可以做 精读或当日回顾。
    详见 👉 http://ksria.com/simpread/docs/#/每日回顾

 - 小书签
    可以在任何浏览器（ Chrome · Firefox · Safari ）将当前页面发送到【简悦 · 稍后读】里面。
    可在【不使用简悦的阅读模式】前提下，就能实现【保存稍后读的轻量级需求】。

 - RSS 阅读器辅助
    为你的【RSS 阅读器】提供：
    - 基于简悦的全文输出（包括： 动态加载页面 或包含 LateX 的页面）
    - 一键保存到简悦 · 稍后读。
    详见 👉 http://ksria.com/simpread/docs/#/RSSReader

 - 稍后读 · 标注的一些优化性改善 👉 http://ksria.com/simpread/welcome/version_2.1.0.html#unreader

更多 2.1.0 的说明详见 👉 http://ksria.com/simpread/welcome/version_2.1.0.html
更多 简悦功能的介绍，请看这里 👉 http://ksria.com/simpread/docs

联系方式：

 - 请订阅简悦的发布通知频道 👉 https://t.me/simpread
 - 简悦的电报群 👉 https://t.me/simpreadgroup

***

我将关闭此 Issues 如有问题请重开。
