### ISSUE TITLE
选项页打开后空白呢

### ISSUE THREAD

**Issue by qq5921** [Kenshin/simpread#1259]
选项页打开后完全空白，chrome和edge都一样，台式机和笔记也一样
![image](https://user-images.githubusercontent.com/21699383/96406318-c1cb4400-1211-11eb-8098-594d12443bcb.png)

**Comment by hexsix** [comment]
+1

控制台消息：
```
Error handling response: TypeError: Cannot read property 'trigger' of undefined
    at n.value (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/options.js:11:20537)
    at c._renderValidatedComponentWithoutOwnerOrContext (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:15045)
    at c._renderValidatedComponent (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:15133)
    at c.mountComponent (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:11383)
    at Object.mountComponent (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:5:6619)
    at g.mountChildren (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:24:3444)
    at g._createContentMarkup (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:21489)
    at g.mountComponent (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:20446)
    at Object.mountComponent (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:5:6619)
    at g.mountChildren (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:24:3444)
    at g._createContentMarkup (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:21489)
    at g.mountComponent (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:20446)
    at Object.mountComponent (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:5:6619)
    at g.mountChildren (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:24:3444)
    at g._createContentMarkup (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:21489)
    at g.mountComponent (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:20446)
```

**Comment by Kenshin** [comment]
@qq5921 

嗨，抱歉，之前的 Issues 太多，导致有一些忘记回复了。

@hexsix @qq5921 

请重新安装你的简悦即可解决。另外，新版（不是 2.0.0 版）会解决这个问题。

**Comment by Kenshin** [comment]
@hexsix 

发生这个情况是因为你之前禁用简悦，近期又开启了造成的吗？
请问你是多久没有使用简悦了？或者说上次使用时的版本是多少？以及方便请告知你的 Chrome 版本。

**Comment by hexsix** [comment]
@Kenshin 

> 发生这个情况是因为你之前禁用简悦，近期又开启了造成的吗？请问你是多久没有使用简悦了？

确实如此，我已经很久没用了，至少半年。

> 或者说上次使用时的版本是多少？

今天我打开的时候自动更新到了2.0.0，所以我不记得上次使用的版本号了、

> 以及方便请告知你的 Chrome 版本。

版本 86.0.4240.198（正式版本） 

重装后 SimpRead 正常了，Thank U

**Comment by Kenshin** [comment]
简悦已升级到 [2.1.0](http://ksria.com/simpread/welcome/version_2.1.0.html) 版本

解决了此类问题，当出现未知错误导致选项页无法打开的话，会提示并可手动下载配置文件，以确保你的数据仍旧留存。

***

简悦 2.1 目前正在做最后一天的折扣 **10元**，有需要的话请前往购买 👉 https://simpread.pro/price.html

***

## 增加了一些新功能：

 - 简悦 · 同步助手
    是随着 简悦 2.1.0 发布的一个全新的【桌面应用】，用于对简悦已知功能的补充，以及会持续提供更多的可玩性，包括：
    - 自动同步
    - 导出到本地任意目录
    - 原生的 PDF · Epub 输出
    - 邮件服务
    - 直接发送到 Kindle
    - 小书签
    详见 👉 http://ksria.com/simpread/docs/#/Sync

 - 自动同步
    通过此功能，简悦可以将【配置文件保存到本地的任意位置】，同时辅以【网盘同步】功能，可以实现自动同步的功能，详见 👉 http://ksria.com/simpread/docs/#/自动同步

 - 授权登录
    简悦的【账户系统】来了，你可以使用【坚果云 或 Dropbox】登录你的【简悦 · 高级账户】了，如何配置，详见 👉 http://ksria.com/simpread/docs/#/授权登录

 - 每日回顾
    简悦会在【每天晚上 19点10分】给你的邮箱发送一封二十四小时以内添加的稍后读，用作当天的每日回顾，同时发送内容也适配了手机端，借此可以做 精读或当日回顾。
    详见 👉 http://ksria.com/simpread/docs/#/每日回顾

 - 小书签
    可以在任何浏览器（ Chrome · Firefox · Safari ）将当前页面发送到【简悦 · 稍后读】里面。
    可在【不使用简悦的阅读模式】前提下，就能实现【保存稍后读的轻量级需求】。

 - RSS 阅读器辅助
    为你的【RSS 阅读器】提供：
    - 基于简悦的全文输出（包括： 动态加载页面 或包含 LateX 的页面）
    - 一键保存到简悦 · 稍后读。
    详见 👉 http://ksria.com/simpread/docs/#/RSSReader

 - 稍后读 · 标注的一些优化性改善 👉 http://ksria.com/simpread/welcome/version_2.1.0.html#unreader

更多 2.1.0 的说明详见 👉 http://ksria.com/simpread/welcome/version_2.1.0.html
更多 简悦功能的介绍，请看这里 👉 http://ksria.com/simpread/docs

联系方式：

 - 请订阅简悦的发布通知频道 👉 https://t.me/simpread
 - 简悦的电报群 👉 https://t.me/simpreadgroup

***

我将关闭此 Issues 如有问题请重开。
