### ISSUE TITLE
稍后读页面内发送到kindle失败

### ISSUE THREAD

**Issue by youngerruan** [Kenshin/simpread#3245]
稍后读页面内发送文章到kindle，显示“开始发送，请稍后”，接着提示框就消失了，实测邮箱发件箱里面没有。
而同一篇文章打开原文后，进入阅读模式，然后发送kindle成功了。邮箱内发件箱有显示。

相关环境：
稍后读内的文章已经自动化到本地html了。不知道是不是这个原因。因为阅读模式下会显示下载中。

**Comment by Kenshin** [comment]
emmm 目前暂时没有可以测试的设备，我找群里面的用户问问。

> 稍后读内的文章已经自动化到本地html了。不知道是不是这个原因。因为阅读模式下会显示下载中。

应该没关系。

***

在此之前，你可以这么测试：

> 先找个正常点的网址 e.g. https://sspai.com/post/69972 然后右键 → 检查 → 打开 DevTools 

1. 在稍后读不要使用本地快照的方式测试（把对应的本地 HTML 删除即可）看看能否成功，以及 DevTools 是否报错？

2. 如果上面测试通过，再试试出问题的 URL，或者多找几个 URL 测试。

3. 把出问题的 URL 给我看下。

**Comment by youngerruan** [comment]
在稍后读有本地快照下，报错如下。（前两条错误点击文章后出现，第三条错误是点击发送 kindle 后出现）

1. `Refused to load the script 'http://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/highlight.min.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://ssl.google-analytics.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`

2. `loader.html:1 Refused to load the script 'http://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/highlight.min.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://ssl.google-analytics.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`

3.
```
main.html:1 Error handling response: TypeError: Cannot read properties of undefined (reading 'forEach')
    at l (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/unreader.js:3:16978)
    at Object.l [as HTML] (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/unreader.js:3:17245)
    at chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/unreader.js:4:16177
    at chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/unreader.js:4:1980
    at Object.g [as SpecialCSS] (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:1:6302)
    at C (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/unreader.js:4:1749)
    at chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/unreader.js:4:16038
    at chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/unreader.js:3:28054
```
---
删除本地快照文件后，稍后读页面内发送kindle还是失败。报错如下
```
main.html:1 Error handling response: TypeError: Cannot read properties of undefined (reading 'forEach')
    at l (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/unreader.js:3:16978)
    at Object.l [as HTML] (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/unreader.js:3:17245)
    at chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/unreader.js:4:16177
    at chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/unreader.js:4:1980
    at Object.g [as SpecialCSS] (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:1:6302)
    at C (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/unreader.js:4:1749)
    at chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/unreader.js:4:16038
    at chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/unreader.js:3:28054
```
是一样的错误。

以上使用的 URL 是你发的那个 URL。

---

> 稍后读内的文章已经自动化到本地 html 了。不知道是不是这个原因。因为阅读模式下会显示下载中。
这个我表述有点问题。是阅读模式下，点击发送 kindle 会显示下载中，然后发送成功。而稍后读模式下，就显示开始发送，然后就没有另外的提示了。

**Comment by Kenshin** [comment]
okay 确实如此，已复现。

我先记 Bug
