### ISSUE TITLE
无法使用简阅保存文章至Joplin，总是提示保存失败。

### ISSUE THREAD

**Issue by DreamerDK** [Kenshin/simpread#3954]
**请说明发生问题的环境**

- 操作系统：  Windows 10

- 浏览器版本：  Edge 101.0.1210.47 

- Joplin版本：2.8.7

- 简悦版本： **2.2.0.520**

**请描述你的问题**

- 在使用简阅保存文章至Joplin时，总是失败。

**截图**

- 1.在Joplin中开启网络剪藏功能
![Snipaste_2022-05-19_22-55-01](https://user-images.githubusercontent.com/5880281/169328576-5c2f601c-dd9c-4085-8e1d-784fc3e98b16.jpg)

- 2.将授权码粘贴至简阅绑定Joplin，提示授权成功，并且此时Joplin中自动创建了一个SimpRead的文件夹。
![Snipaste_2022-05-19_22-55-16](https://user-images.githubusercontent.com/5880281/169328312-2b88cd4d-3de8-4bbd-8b62-860538d05c02.jpg)

- 3.在网站中使用保存到Joplin功能，提示保存失败，Joplin中的SimpRead也是空的。
![Snipaste_2022-05-19_22-54-15](https://user-images.githubusercontent.com/5880281/169328518-c171bbb7-834a-4bb0-b1f6-fb94bd2d7967.jpg)

- 4.在issue中搜索方案，尝试了 [#1895](https://github.com/Kenshin/simpread/discussions/1895) 中提到的方法，均无法解决这一问题。

- PS：在授权时，简阅可以在Joplin中自动创建SimpRead文件夹，说明两者间应当是可以“联通”的（我试了好几次，授权时都能成功创建），但不知为何保存总是失败。

**Comment by DreamerDK** [comment]
怀疑是使用测试版的原因，又尝试使用[v2.7.15](https://github.com/laurent22/joplin/releases/tag/v2.7.15)，便携版本[JoplinPortable.exe](https://github.com/laurent22/joplin/releases/download/v2.7.15/JoplinPortable.exe)。
是一样的结果。

**Comment by Kenshin** [comment]
emmm 能否试试更低版本的测试下？看看是什么原因？

**Comment by DreamerDK** [comment]
又试了更早的[v2.6.9](https://github.com/laurent22/joplin/releases/tag/v2.6.9) ，问题依旧。
（[v2.7.15](https://github.com/laurent22/joplin/releases/tag/v2.7.15)是最新的正式版本，在使用2.6.9时会提示更新，还尝试使用更早的2.3.5，但好像数据不能兼容新版了，会报错，所以没有再尝试了）。

因为只有一台电脑，没有其他电脑测试，所以我不能确定是否是个人电脑的问题，还是现在两者间的这个功能就是无法使用了。

附 http://[localhost:41184](http://localhost:41184/)/的信息，不知道是否对解决问题有所帮助。
`
{"error":"Not Found: \n\nError: Not Found\n    at Api.<anonymous> (C:\\Programs\\Joplin\\resources\\app.asar\\node_modules\\@joplin\\lib\\services\\rest\\Api.js:107:23)\n    at Generator.next (<anonymous>)\n    at C:\\Programs\\Joplin\\resources\\app.asar\\node_modules\\@joplin\\lib\\services\\rest\\Api.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Programs\\Joplin\\resources\\app.asar\\node_modules\\@joplin\\lib\\services\\rest\\Api.js:4:12)\n    at Api.route (C:\\Programs\\Joplin\\resources\\app.asar\\node_modules\\@joplin\\lib\\services\\rest\\Api.js:100:16)\n    at ClipperServer.<anonymous> (C:\\Programs\\Joplin\\resources\\app.asar\\node_modules\\@joplin\\lib\\ClipperServer.js:168:58)\n    at Generator.next (<anonymous>)\n    at C:\\Programs\\Joplin\\resources\\app.asar\\node_modules\\@joplin\\lib\\ClipperServer.js:8:71\n    at new Promise (<anonymous>)"}
`

**Comment by Kenshin** [comment]
emmm 因为我不是 Joplin 用户，所以只是为了测试使用过，刚才测试了下，

这个版本是好使的（但是确实有点老了，哈哈）

![image](https://user-images.githubusercontent.com/81074/169486316-a0314227-a028-4a4d-adb6-ea51ffc76255.png)

我的意思是：要是有可能试试更低的版本。

**Comment by Kenshin** [comment]
okay 我回头找个新版本测试下。
