### ISSUE TITLE
请问一下怎么打包啊,mac下有试过么，打包出现下面异常

### ISSUE THREAD

**Issue by fatihwk** [Kenshin/simpread#42]
./npmw run publish
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn run ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

**Comment by Kenshin** [comment]
哦~ 搞定了？
