### ISSUE TITLE
关于插件管理器的一些疑问

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simpread#4253]
使用了这个插件之后，是不是以后新的插件都要使用它来安装？

自动同步是否还能开启？

_Originally posted by @Stark-X in https://github.com/Kenshin/simpread/discussions/4221#discussioncomment-3218437_

**Comment by Kenshin** [comment]
@Stark-X 

我帮你新建了一个 Issues 来讨论。

> 使用了这个插件之后，是不是以后新的插件都要使用它来安装？

并无冲突，但一般来说使用此插件安装的前提：无法正常安装。所以建议还是通过此插件安装。

> 自动同步是否还能开启？

**仅安装此插件时需要关闭自动同步**，通过此插件安全其它插件时不需要关闭同步助手。

**Comment by Stark-X** [comment]
新的问题，发现 版面宽度定制器选项 无法添加任何配置，点击“添加”按钮，在 DevTools 里有如下报错

```
VM307:41 
        
Uncaught TypeError: Cannot read properties of undefined (reading 'push')
    at HTMLAnchorElement.add (eval at c (contentscripts.js:6:17653), <anonymous>:41:36)
    at HTMLHtmlElement.dispatch (common.js:7:20091)
    at g.handle (common.js:7:16836)
add @ VM307:41
dispatch @ common.js:7
g.handle @ common.js:7
```

**Comment by Kenshin** [comment]
> 发现 版面宽度定制器选项 无法添加任何配置，点击“添加”按钮，在 DevTools 里有如下报错

嗨，同样我也没有遇到，建议在 https://sspai.com/post/69972 测试。

**Comment by Stark-X** [comment]
一样的结果

这次我提前打开 DevTools，在点击 “版面宽度定制器” 触发弹窗时，会有以下错误：

```
Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
    at layouts (eval at c (contentscripts.js:6:17653), <anonymous>:104:32)
    at upateLayouts (eval at c (contentscripts.js:6:17653), <anonymous>:120:18)
    at popup (eval at c (contentscripts.js:6:17653), <anonymous>:77:5)
    at eval (eval at c (contentscripts.js:6:17653), <anonymous>:10:48)
    at Object.l [as Event] (contentscripts.js:6:17458)
    at n.value (contentscripts.js:15:9780)
    at Object.onAction (contentscripts.js:15:15281)
    at onClick (contentscripts.js:15:5374)
    at Object.r (vendors.js:13:17136)
    at a (vendors.js:24:4169)
    at Object.s [as executeDispatchesInOrder] (vendors.js:24:4380)
    at p (vendors.js:10:11008)
    at f (vendors.js:10:11134)
    at Array.forEach (<anonymous>)
    at n (vendors.js:13:24607)
    at Object.processEventQueue (vendors.js:10:12254)
```

**Comment by Kenshin** [comment]
安装其它插件呢？

**Comment by Stark-X** [comment]
- 阅读模式版面定制器正常工作，但是好像“第一次使用简悦？”的提示就是在第一次编辑它的设置保存并刷新之后触发的
- LightBoxGallery 没报错，可以编辑选项，但是保存不生效，插件本身的功能也失效了

其它没试，以上在 Windows 10 + Edge latest、MacOS + Chrome lastest 的环境，是一样的表现

**Comment by Kenshin** [comment]
> 阅读模式版面定制器正常工作，但是好像“第一次使用简悦？”的提示就是在第一次编辑它的设置保存并刷新之后触发的

点击不再显示后，应该正常不会再显示了。

> LightBoxGallery 没报错，可以编辑选项，但是保存不生效，插件本身的功能也失效了

保存不生效的问题是因为某个隐形 Bug 造成的，开发插件触发器就是为了这个问题，所以使用插件触发器保存配置即可。

**Comment by Kenshin** [comment]
嗨，插件管理器更新到 2.0.0 

## 彻底解决：

1️⃣ 无法安装插件

2️⃣ 安装插件后插件的配置保存不生效

的问题。

## 一站式教程（含下载地址）

https://www.yuque.com/kenshin/simpread/fcw60u

## 注意

并不是【用同步助手的自动同步功能】后 100% 无法安装插件，如果你遇到了此问题，可以使用此插件解决。

## 视频操作

https://user-images.githubusercontent.com/81074/180121389-550ccfbc-52b3-4d17-996c-125071746a26.mp4

**Comment by Stark-X** [comment]
版面宽度定制器 还是不能正常工作，点击 “添加” 没反应
开发者工具报错：
```
Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
    at layouts (eval at c (contentscripts.js:6:17653), <anonymous>:104:32)
    at upateLayouts (eval at c (contentscripts.js:6:17653), <anonymous>:120:18)
    at popup (eval at c (contentscripts.js:6:17653), <anonymous>:77:5)
    at eval (eval at c (contentscripts.js:6:17653), <anonymous>:10:48)
    at Object.l [as Event] (contentscripts.js:6:17458)
    at n.value (contentscripts.js:15:9780)
    at Object.onAction (contentscripts.js:15:15281)
    at onClick (contentscripts.js:15:5374)
    at Object.r (vendors.js:13:17136)
    at a (vendors.js:24:4169)
    at Object.s [as executeDispatchesInOrder] (vendors.js:24:4380)
    at p (vendors.js:10:11008)
    at f (vendors.js:10:11134)
    at Array.forEach (<anonymous>)
    at n (vendors.js:13:24607)
    at Object.processEventQueue (vendors.js:10:12254)
```

```
Uncaught TypeError: Cannot read properties of undefined (reading 'push')
    at HTMLAnchorElement.add (eval at c (contentscripts.js:6:17653), <anonymous>:41:36)
    at HTMLHtmlElement.dispatch (common.js:7:20091)
    at g.handle (common.js:7:16836)
add @ VM143:41
dispatch @ common.js:7
g.handle @ common.js:7
```

**Comment by Kenshin** [comment]
@Stark-X 

请在 https://sspai.com/post/69972 测试，如果之前安装过插件的话，建议先清除全部插件

<img width="774" alt="image" src="https://user-images.githubusercontent.com/81074/192186501-fbdff719-52cf-46fd-a515-fd4736025b16.png">

**Comment by Stark-X** [comment]
> @Stark-X
> 
> 请在 https://sspai.com/post/69972 测试，如果之前安装过插件的话，建议先清除全部插件
> 
> <img alt="image" width="774" src="https://user-images.githubusercontent.com/81074/192186501-fbdff719-52cf-46fd-a515-fd4736025b16.png">

今天再做了一次，只安装 “版面宽度定制器”，还是一样的结果

**Comment by Kenshin** [comment]
@Stark-X 

插件管理器能使用吧？如果能的话，在插件管理器中删除「版面宽度定制器」。

再或者更换一个浏览器，然后安装简悦以及版面宽度定制器，其他的不要设置，在试试是否能用？

还有，使用版面宽度定制后你要做什么？这个插件一般是针对多个屏幕设备的用户准备的。

**Comment by Stark-X** [comment]
试着试着，出了另外的幺蛾子，安装了“插件管理器”的情况下，插件补丁里能看到“插件管理器”，动作里看不到了


版面宽度定制 就是我提的需求呀，有两个屏幕，其中一个屏幕是竖着的

**Comment by Kenshin** [comment]
> 安装了“插件管理器”的情况下，插件补丁里能看到“插件管理器”

你太能折腾了... 我不是都告诉你了吗？

**更换一个浏览器，然后安装简悦以及版面宽度定制器，其他的不要设置，试试是否能用？**

PS：如果还是不行的话，就按照这个方式录屏给我瞧瞧。

> 版面宽度定制 就是我提的需求呀，有两个屏幕，其中一个屏幕是竖着的

哈哈，这个插件去年就开发了，竟然才继续讨论。 😂

**Comment by Kenshin** [comment]
另外，我看了下 https://github.com/Kenshin/simpread/issues/4253#issuecomment-1257412630 提到的报错，感觉跟简悦无关。

**Comment by Stark-X** [comment]
> 哈哈，这个插件去年就开发了，竟然才继续讨论。 😂

这不是因为我提议使用 `@media` 实现，一直没后文嘛
然后不知道什么时候开始配置一直保存失败，就等着这个“插件管理器”更新能不能修复，一直等到现在。。

想着你个人开发可能会非常忙，我这情况估计也是少见，就没催更

**Comment by Kenshin** [comment]
> 不知道什么时候开始配置一直保存失败，就等着这个“插件管理器”更新能不能修复

估计是你太折腾配置造成的，所以... 我已经回复你了：

1. 错误跟简悦无关 https://github.com/Kenshin/simpread/issues/4253#issuecomment-1259295172
2. 更换一个浏览器，然后安装简悦以及版面宽度定制器，其他的不要设置，在试试是否能用？

**Comment by Stark-X** [comment]
尝试了多次之后，发现大概是跟 simpread_config.json 没正确更新 `plugins` 有关系。

我做了下面的操作：
1. 删除插件
2. 重置所有配置
3. 重新授权高级账户
4. 安装“插件管理器”
5. 开启自动同步，“插件管理器”在动作里就没了，直接安装其它插件也是一样的结果。

或者：第4步，换成开启自动同步后，直接安装“版面宽度定制器”，“动作”里也是没有插件的配置项。

以上两个流程的结果都是 simpread_config.json 里的 `plugins` 为空，然后，我按了一下配置页面里的“通过同步助手覆盖本地配置文件”后，在文章页面进入阅读模式，“版面宽度定制器选项”立刻就弹出来了，插件的配置也正常了，开发者工具里也没有再出现上面我提到的 异常，`plugins` 里也有插件的id出现在里面了。

**Comment by Kenshin** [comment]
1. 步骤1：**之前需要重新安装简悦**，而不是仅进只是重置（仅针对你自己，跟其它用户无关）
2. 步骤4：**安装插件管理器后的步骤是错误的**。（插件管理器有使用说明，但你可能没有留意...）简单的说，安装完插件管理器后，通过它安装插件，同时不用手动开启自动同步，通过它安装插件后会自动开启自动同步并将正确的配置文件保存到本地。

所以，你遇到的问题有两个：

1. 没有按照我的建议测试...
2. 没有留意插件管理器的用法（其实我在上面也提到了...

如果你想要配置成功，建议按照我的方式：

**更换一个浏览器，然后安装简悦以及版面宽度定制器，其他的不要设置，在试试是否能用？**

这么做的目的是为了用最小环境来验证你的使用是否正确。当你的使用正确后，再按照正常的方式（也就是你提到的方式安装插件管理器）

综上。

**Comment by Stark-X** [comment]
我是看到“注意事项”里写着：
- 仅安装此插件时才需要关闭自动同步。 
- 通过此插件安装其他插件时，**不需要关闭自动同步**。

我理解成了关闭同步后，安装完“插件管理器”，再去把自动同步手动开启了。
“插件管理器”里写的“安装此插件后无需人工干预，自动解决”也没理解对，原来是会自动重新开启自动同步的意思啊。

在公司的电脑不好截图录屏上传，回到家里用 Mac，通过插件管理器能正常安装插件，配置文件里的 plugins 也正确更新写到本地配置文件里了。

安装了“lightbox Gallery”、“版面宽度定制器”、“阅读模式浮动面板定制器”，除了“版面宽度定制器”之外，都正确保存配置了，刷新页面也没问题，点击“版面宽度定制器”的配置时，开发者工具有报错：
<img width="391" alt="image" src="https://user-images.githubusercontent.com/13653522/192798888-8ee1db2b-dd65-43a8-accd-5c3548576f01.png">

前后的两个`new plugin value`是其它插件保存时输出的，堆栈报错是点击 “版面宽度定制器”的配置时的输出

<img width="486" alt="image" src="https://user-images.githubusercontent.com/13653522/192799297-9cb118cd-b067-463b-9ca1-f10451d48b41.png">


https://user-images.githubusercontent.com/13653522/192802391-04d91607-b4a1-4bd0-b94a-3d688350bb8b.mp4

**Comment by Kenshin** [comment]
哈，真不容易，解决了「插件管理器」的问题…

版面布局的问题，我明天再确认下。

**Comment by Stark-X** [comment]
修复了！！
