### ISSUE TITLE
webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead

### ISSUE THREAD

**Issue by rinetd** [Kenshin/simpread#480]
使用 webpack4 报错
```
webpack --devtool=source-map --progress --colors --watch
D:\node\simpread\node_modules\webpack-cli\bin\cli.js:231
                                throw err;
                                ^

Error: webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead.
    at Object.get [as CommonsChunkPlugin] (D:\node\simpread\node_modules\webpack\lib\webpack.js:185:10)
    at Object.<anonymous> (D:\node\simpread\webpack.config.js:13:28)
    at Module._compile (D:\node\simpread\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (D:\node\simpread\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (D:\node\simpread\node_modules\webpack-cli\bin\convert-argv.js:115:13)
    at requireConfig (D:\node\simpread\node_modules\webpack-cli\bin\convert-argv.js:117:6)
    at D:\node\simpread\node_modules\webpack-cli\bin\convert-argv.js:124:17
    at Array.forEach (<anonymous>)
    at module.exports (D:\node\simpread\node_modules\webpack-cli\bin\convert-argv.js:122:15)
    at yargs.parse (D:\node\simpread\node_modules\webpack-cli\bin\cli.js:228:39)
    at Object.parse (D:\node\simpread\node_modules\webpack-cli\node_modules\yargs\yargs.js:567:18)
    at D:\node\simpread\node_modules\webpack-cli\bin\cli.js:206:8
    at Object.<anonymous> (D:\node\simpread\node_modules\webpack-cli\bin\cli.js:505:3)i.js:505:3)
    at Module._compile (internal/modules/cjs/loader.js:738:30)             )
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)    at require (internal/modules/cjs/helpers.js:20:18)
    at module.exports.filename (C:\Users\admin\scoop\persist\nodejs\bin\node_modules\webpack-cli\node_modules\import-local\index.js:16:66)
    at C:\Users\admin\scoop\persist\nodejs\bin\node_modules\webpack-cli\bin\cli.js:13:6    at Object.<anonymous> (C:\Users\admin\scoop\persist\nodejs\bin\node_modules\webpack-cli\bin\cli.js:505:3)
    at Module._compile (internal/modules/cjs/loader.js:738:30)    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)

D:\node\simpread>D:\node\simpread>webpack --version
4.29.6
```

**Comment by Kenshin** [comment]
Webpack 每个版本之间的差异很大。

你可以看看 `package.json` 里面的 `devDependencies` 依赖说明。
