### ISSUE TITLE
授权提示一直转圈，不跳出page

### ISSUE THREAD

**Issue by shankoubaifei** [Kenshin/simpread#5085]
Error handling response: TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at a.value (eval at c (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/contentscripts.js:6:17653), <anonymous>:53:3805)
    at eval (eval at c (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/contentscripts.js:6:17653), <anonymous>:53:4392)

**Comment by Kenshin** [comment]
嗨，试试 https://github.com/Kenshin/simpread/discussions/4954 这个方案。
