### ISSUE TITLE
保存至joplin失败

### ISSUE THREAD

**Issue by hiby-arch** [Kenshin/simpread#5340]
### 描述这个错误

在本机电脑上，保存至joplin失败。任何网站都是。原来曾经正常过
1. 若直接用joplin web clipper官方插件无问题
2. 已复位，已重装，直接用浏览器打开http://localhost:41184/ 应该是无问题
{"error":"Not Found: \n\nError: Not Found\n    at Api.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/rest/Api.js:107:23)\n    at Generator.next (<anonymous>)\n    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/rest/Api.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/rest/Api.js:4:12)\n    at Api.route (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/rest/Api.js:100:16)\n    at ClipperServer.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/ClipperServer.js:168:58)\n    at Generator.next (<anonymous>)\n    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/ClipperServer.js:8:71\n    at new Promise (<anonymous>)"}
3. 通过chrome调试，错误如图：
![image](https://user-images.githubusercontent.com/77217310/225821114-c1673c23-04e1-4257-8150-ebfdc4a8f4b6.png)
![image](https://user-images.githubusercontent.com/77217310/225821607-bacd4c9e-8dd8-470d-a7c0-ba6fecc02847.png)

### 复现步骤

参见上述

### 操作系统

macOS

### 浏览器

chrome

### 发生问题的网址

any

**Comment by Kenshin** [comment]
emmm

既然之前好使的话，在**隐身模式下仅使用简悦的方式**，排除其它扩展的干扰。

另外一点：选项页 → 服务 → joplin 授权时什么提示？
