### ISSUE TITLE
导出到 Obsidian 失败

### ISSUE THREAD

**Issue by moleoxa** [Kenshin/simpread#6471]
### 描述这个错误

```log
docs/#/:57 Access to script at 'http://cdn.staticfile.org/docsify/4.10.2/plugins/zoom-image.min.js' from origin 'http://ksria.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
docs/:92 
        
        
       GET http://cdn.staticfile.org/docsify/4.10.2/plugins/zoom-image.min.js net::ERR_FAILED
docs/#/:57 Access to script at 'http://cdn.staticfile.org/docsify/4.10.2/plugins/search.min.js' from origin 'http://ksria.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
docs/:94 
        
        
       GET http://cdn.staticfile.org/docsify/4.10.2/plugins/search.min.js net::ERR_FAILED
index.js:2910 Uncaught (in promise) DOMException: Failed to execute 'atob' on 'Window': The string to be decoded contains characters outside of the Latin1 range.
    at tryConvertDataURLToBlobSync (chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/inject/index.js:2910:28)
    at tryConvertDataURLToBlobURL (chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/inject/index.js:2926:20)
    at chrome-extension://eimadpbcbfnmbkopoojfekhnkhdbieeh/inject/index.js:3487:47
    at async Promise.all (index 0)
tryConvertDataURLToBlobSync @ index.js:2910
tryConvertDataURLToBlobURL @ index.js:2926
(anonymous) @ index.js:3487
Promise.then (async)
handleAsyncDeclaration @ index.js:5201
(anonymous) @ index.js:5300
(anonymous) @ index.js:5295
modifySheet @ index.js:5176
buildOverrides @ index.js:5853
render @ index.js:5866
(anonymous) @ index.js:7446
(anonymous) @ index.js:7445
handleStyleOperations @ index.js:6207
handleMinorTreeMutations @ index.js:6234
(anonymous) @ index.js:479
(anonymous) @ index.js:478
Show 15 more frames
Show less
docs/:108 https://simpread-1254315611.cos.ap-shanghai.myqcloud.com/static/docs/new.png
docs/:108 https://simpread-1254315611.cos.ap-shanghai.myqcloud.com/static/docs/assets/feature%202.1.0.png
VM122:347 simpread obsidian fail  {jqXHR: {…}, textStatus: 'error', errorThrown: ''}errorThrown: ""jqXHR: readyState: 0status: 0statusText: "error"[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()textStatus: "error"[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
```

### 操作系统

Windows

### 浏览器

Chrome

### 发生问题的网址

https://github.phodal.com/#/chapter/Github%E6%BC%AB%E6%B8%B8%E6%8C%87%E5%8D%97

**Comment by Kenshin** [comment]
详细说明下你的问题… 😂

**Comment by moleoxa** [comment]
> 详细说明下你的问题… 😂

使用的极速版配置。其它网站正常，这个网站 aa 然后动作导入到 Obsidian 提示失败，你试试？

**Comment by Kenshin** [comment]
emmm 已确认这个问题。

极速版在个别页面存在无法导入的情况，因为极速版使用了 `Local REST API` 方案，而这个方案有些弊端，

PS：简悦的高级版方案测试是没问题的，可以正常导入。
