### ISSUE TITLE
同步助手基础导出方案PDF导出失败，控制台报错

### ISSUE THREAD

**Issue by darkxinyu** [Kenshin/simpread#6536]
### 描述这个错误

使用同步助手基础导出方案导出PDF时，右上角会闪现“正在导出，请稍候”之类的提示，但实际并没有执行任何操作，同步助手那边并未看到接收到导出任务的日志，同时浏览器控制台有报错，所有网站均如此

Error handling response: TypeError: Cannot read properties of undefined (reading 'status')
    at I (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/contentscripts.js:3:25417)
    at chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/contentscripts.js:4:5322
    at chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:2:8989
69972:1 Error in event handler: TypeError: Cannot read properties of undefined (reading 'code')
    at o (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/common.js:3:21134)
    at chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/common.js:3:24548

![WX20240606-104125@2x](https://github.com/Kenshin/simpread/assets/688257/86d4a06d-7ef3-4ea2-ab42-fc50b10fdaac)

### 复现步骤

1、打开网页
2、进入阅读、聚焦或稍后读模式
3、导出为PDF

### 其他相关说明

浏览器方案和高级导出方案导出PDF均无问题，就是PDF导出插件右下角图标有时死活出不来，得删除重装插件才恢复

### 操作系统

macOS Sonoma 14.5

### 浏览器

Arc浏览器 1.44.3 (50502)

### 发生问题的网址

https://sspai.com/post/69972

**Comment by Kenshin** [comment]
emmm 这个错误应该跟 PDF 无关。

我看到你使用的是 Arc 浏览器，试试 Chrome 是否存在相同问题？

PS：如果对 PDF 有严格要求的话，其实更建议使用 [PDF 高级打印方案](https://github.com/Kenshin/simpread/discussions/3887) 我看到你是 Mac 系统，配置起来应该很简单。

**Comment by darkxinyu** [comment]
> emmm 这个错误应该跟 PDF 无关。
> 
> 我看到你使用的是 Arc 浏览器，试试 Chrome 是否存在相同问题？
> 
> PS：如果对 PDF 有严格要求的话，其实更建议使用 [PDF 高级打印方案](https://github.com/Kenshin/simpread/discussions/3887) 我看到你是 Mac 系统，配置起来应该很简单。

Chrome Version 125.0.6422.142 (Official Build) (arm64)，同样的现象，控制台也是报同样的错误

PDF高级打印方案可以用，只是觉得既然有这么个功能，出了问题，还是希望能得到解决，也是可以多一个方案尝试，可能有些网页基础的打印效果更好呢

**Comment by Kenshin** [comment]
> Chrome Version 125.0.6422.142 (Official Build) (arm64)，同样的现象，控制台也是报同样的错误

> PDF高级打印方案可以用，只是觉得既然有这么个功能，出了问题，还是希望能得到解决

当然，有问题自然是需要解决的 😂

只是，我这边没有此问题，我再详细测试下，有需要的话，可能需要你提供配置文件给我（暂时不用）
