### ISSUE TITLE
Chrome 选项菜单页报错,导致无法使用选项菜单

### ISSUE THREAD

**Issue by earneet** [Kenshin/simpread#994]
当我尝试绑定账号激活高级时遇到此问题。
Chrome Ver  84.0.4147.135（正式版本） （64 位）
简悦当前最新版本， 点击选项菜单后打开的页面报告如下错误日志， 页面无内容
```
options.html:1 Error handling response: TypeError: Cannot read property 'trigger' of undefined
    at n.value (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/options.js:11:20537)
    at c._renderValidatedComponentWithoutOwnerOrContext (chro
[ijllcpnolfcooahcekpamkbidhejabll-1598321110331.log](https://github.com/Kenshin/simpread/files/5120998/ijllcpnolfcooahcekpamkbidhejabll-1598321110331.log)
![微信截图_20200825101201](https://user-images.githubusercontent.com/6070491/91114882-7be37b00-e6bb-11ea-9c89-917ca26ac38c.png)

me-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:15045)
    at c._renderValidatedComponent (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:15133)
    at c.mountComponent (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:11383)
    at Object.mountComponent (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:5:6619)
    at g.mountChildren (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:24:3444)
    at g._createContentMarkup (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:21489)
    at g.mountComponent (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:20446)
    at Object.mountComponent (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:5:6619)
    at g.mountChildren (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:24:3444)
    at g._createContentMarkup (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:21489)
    at g.mountComponent (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:20446)
    at Object.mountComponent (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:5:6619)
    at g.mountChildren (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:24:3444)
    at g._createContentMarkup (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:21489)
    at g.mountComponent (chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/vendors.js:23:20446)
```

**Comment by Kenshin** [comment]
谢谢反馈

https://github.com/Kenshin/simpread/issues/908 请使用 问题6 给出的方案。
